name: bomberman-rl
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _sysroot_linux-64_curr_repodata_hack=3
  - alsa-lib=1.2.13
  - aom=3.6.0
  - attr=2.5.1
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - cairo=1.16.0
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - cloudpickle=3.0.0
  - configargparse=1.4
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cuda-version=12.4
  - dav1d=1.2.1
  - dbus=1.13.18
  - expat=2.6.3
  - farama-notifications=0.0.4
  - ffmpeg=4.3
  - filelock=3.13.1
  - fluidsynth=2.3.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freetype=2.12.1
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - graphite2=1.3.14
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - gymnasium=0.28.1
  - harfbuzz=8.2.1
  - icu=73.2
  - idna=3.7
  - intel-openmp=2023.1.0
  - jack=1.9.22
  - jax-jumpy=1.0.0
  - jinja2=3.1.4
  - jpeg=9e
  - kernel-headers_linux-64=3.10.0
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libavif=0.11.1
  - libcap=2.69
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdb=6.2.32
  - libdeflate=1.17
  - libexpat=2.6.3
  - libffi=3.4.4
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=14.2.0
  - libgcrypt=1.11.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libgpg-error=1.51
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libmad=0.15.1b
  - libmpdec=4.0.0
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.39
  - libsndfile=1.2.2
  - libsqlite=3.46.0
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=256.7
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.1
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpg123=1.32.9
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.3
  - numpy=1.26.4
  - numpy-base=1.26.4
  - ocl-icd=2.3.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.4.0
  - opusfile=0.12
  - pcre2=10.42
  - pip=24.2
  - pixman=0.40.0
  - portaudio=19.6.0
  - portmidi=2.0.4
  - pthread-stubs=0.3
  - pulseaudio-client=17.0
  - pybind11-abi=5
  - pygame=2.1.3.dev8
  - pysocks=1.7.1
  - python=3.11.10
  - python_abi=3.11
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - scipy=1.14.1
  - sdl2=2.30.7
  - sdl2_image=2.6.3
  - sdl2_mixer=2.6.3
  - sdl2_ttf=2.20.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - sysroot_linux-64=2.17
  - tbb=2021.8.0
  - tk=8.6.14
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024b
  - urllib3=2.2.3
  - wheel=0.44.0
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-xorgproto=2024.1
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - cfgv==3.4.0
      - click==8.1.7
      - contourpy==1.3.1
      - cycler==0.12.1
      - decorator==5.1.1
      - distlib==0.3.9
      - fonttools==4.55.0
      - fsspec==2024.10.0
      - identify==2.6.2
      - imageio==2.36.0
      - imageio-ffmpeg==0.5.1
      - kiwisolver==1.4.7
      - lz4==4.3.3
      - matplotlib==3.9.2
      - moviepy==2.0.0
      - mypy-extensions==1.0.0
      - nodeenv==1.9.1
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opencv-python==4.10.0.84
      - packaging==24.2
      - pathspec==0.12.1
      - pdoc==15.0.0
      - pillow==10.4.0
      - platformdirs==4.3.6
      - proglog==0.1.10
      - pygments==2.18.0
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - six==1.16.0
      - sympy==1.13.1
      - torch==2.5.1
      - tqdm==4.67.0
      - triton==3.1.0
      - virtualenv==20.27.1
